---
# Variables that the user needs to set
user: deault
github:
  name: default
  email: default@example.com

# Variables that the user can set to customize
repos_folder: Projects
additional_folders:
optional_packages: 
optional_pip_libraries: 
optional_npm_packages:
private_dotfiles_url: 

# Variables the user shouldn't try to change
dotfiles_repo_url: git@github.com:tiannaru/dotfiles.git
mandatory_packages:
  - bat
  - fd
  - exa
  - fish
  - vim
  - fzf
  - npm
  - ripgrep
  - tmux
  - xclip
  - yarn
  - yay
  - lazygit
  - kitty
  - stow
  - make
  - fakeroot

mandatory_pip_libraries:
  - virtualenv
  - black
  - yamllint
  - ansible-lint
  - flake8
  - pylint

mandatory_npm_packages:
  - neovim

backup_targets:
  - ~/.config/fish
  - ~/.config/kitty
  - ~/.config/nvim
  - ~/.config/lvim
  - ~/.config/ranger
  - ~/.tmux.conf
  - ~/.config/vim
  - ~/.xinitrc
  - ~/.xprofile
  - ~/.Xresources

# Platform dependent
vagrant:
server:
desktop:
  yay_packages:
    - otf-monego-git

